library(
    identifier: 'jenkins-shared-library@module-8.1',
    retriever: modernSCM([
        $class: 'GitSCMSource',
        remote: 'https://github.com/PashaRom/report-portal-selenium-testing.git'
    ])
)

pipeline{
    agent any


    stages{
         stage('Setup') {
            steps{
                script{

                    dotnetVersion()

                    dotnetRestore("${env.PROJECT_DIR}")
                }
            }
        }
    }
}