library(
    identifier: 'jenkins-shared-library@module-8.1',
    retriever: modernSCM([
        $class: 'GitSCMSource',
        remote: 'https://github.com/PashaRom/report-portal-selenium-testing.git'
    ])
)

pipeline {
    agent any

    
    options {
        buildDiscarder(logRotator(
            numToKeepStr: '10'
        ))
    }

    
    
    parameters {
        booleanParam(name: 'CHROME',  defaultValue: true,  description: 'Run Chrome')
        booleanParam(name: 'EDGE',    defaultValue: false, description: 'Run Edge')
        booleanParam(name: 'FIREFOX', defaultValue: false, description: 'Run Firefox')
        
        choice(
            name: 'HEADLESS_MODE',
            choices: ['HEADLESS', 'NON_HEADLESS'],
            description: 'Browser mode'
        )

        string(
            name: 'THREADS',
            defaultValue: '3',
            description: 'Number of parallel test threads'
        )

        string(
            name: 'TEST_FILTER',
            defaultValue: 'FullyQualifiedName~Cancel_ClosesDialog',
            description: 'dotnet test filter (например: TestCategory=dashboard_crud)'
        )

        string(
            name: 'GIT_BRANCH',
            defaultValue: 'main',
            description: 'Git branch to build'
        )
    }

    
    environment {
            BASE_URL = "${env.RP_BASE_URL}"
            PROJECT_DIR = 'SeleniumFrameworkInteraction'
            REMOTE_URL = "${env.RP_REMOTE_URL}"
            TEST_RESULTS_DIR = 'test-results'
            ALLURE_RESULTS_DIR = 'UITests/bin/Debug/net8.0/allure-results'
            REPORT_PORTAL_URL = "${env.REPORT_PORTAL_URL}"
    }

    stages { 

        stage('Setup') {
            steps{
                script{
                    gitCheckout(params.GIT_BRANCH, 'https://github.com/PashaRom/report-portal-selenium-testing.git')

                    dotnetVersion()

                    dotnetRestore("${env.PROJECT_DIR}")
                }
            }
        }
        

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    dir("${env.PROJECT_DIR}") {
                        withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                            sh '''                            
                            
                            dotnet new tool-manifest || true
                            dotnet tool install dotnet-sonarscanner || true
                            dotnet tool restore

                            dotnet tool run dotnet-sonarscanner begin \
                                /k:"selenium-framework" \
                                /d:sonar.login="$SONAR_TOKEN" \
                                /n:"Selenium Framework" \
                                /d:sonar.tests=UITests \
                                /d:sonar.sources=Core,Business

                            dotnet build --no-restore

                            dotnet tool run dotnet-sonarscanner end \
                                /d:sonar.login="$SONAR_TOKEN"

                            '''
                        }
                    }
                }
            }
        }
        
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    script {
                        def qg = waitForQualityGate()
                        if (qg.status != 'OK') {
                            unstable("Quality Gate failed: ${qg.status}")
                        }
                    }
                }
            }
        }
        
        stage('Test (Selenoid)') {
            steps {
                script {
                    sh "rm -rf ${env.PROJECT_DIR}/UITests/bin/Debug/net8.0/${env.ALLURE_DIR}"
                    
                    def browsers = []

                    if (params.CHROME)  browsers.add('Chrome')
                    if (params.EDGE)    browsers.add('Edge')
                    if (params.FIREFOX) browsers.add('Firefox')

                    
                    if (browsers.isEmpty()) {
                        error("No browsers selected!")
                    }

                    def parallelStages = [:]
                    
                    for (browser in browsers) {
                        def b = browser
                      
                        parallelStages[b] = {
                            stage("Run on ${b}") {
                                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                                    dir("${env.PROJECT_DIR}/UITests") {
                                        withCredentials([string(credentialsId: 'RP_API_KEY', variable: 'RP_KEY')]) {
                                            sh """
                                            BROWSERS=${b} \\
                                            BaseUrl=${env.BASE_URL} \\
                                            DriverSettings__Remote=true \\
                                            DriverSettings__Headless=${params.HEADLESS_MODE == 'HEADLESS'} \\
                                            ReportPortal__Launch__Name="RP UI NUnit - ${b}" \\
                                            REPORTPORTAL_SERVER_APIKEY=\$RP_KEY \\
                                            dotnet test --no-build \\
                                                --results-directory ${env.TEST_RESULTS_DIR}/${b} \\
                                                --filter "${params.TEST_FILTER}" \\
                                                -- NUnit.NumberOfTestWorkers=${params.THREADS}
                                            """
                                        }
                                    }
                                }
                            }
                        }
                    }

                    parallel parallelStages
                }
            }
        }

        stage('Publish Allure') {
            steps {
                script {
                    step([
                        $class: 'AllureReportPublisher',
                        results: [
                            [path: "${env.PROJECT_DIR}/${env.ALLURE_RESULTS_DIR}**"]
                        ]
                    ])
                }
            }
        }

    }
    post {
        always {
            archiveArtifacts artifacts: "${env.PROJECT_DIR}/${env.ALLURE_RESULTS_DIR}/**"
        }
    }
}
